onboarding = false

[theme]
name = "kanagawa"
auto_switch = false

[ui]
status_indicators = "symbols"

[ui.toast]
delivery = "herdr"

[keys]

# Pane navigation
focus_pane_left = "alt+h"
focus_pane_down = "alt+j"
focus_pane_up = "alt+k"
focus_pane_right = "alt+l"

# Pane lifecycle and layout
close_pane = "alt+w"
split_vertical = "alt+5"
split_horizontal = "alt+6"

# Tabs and session navigation
goto = "alt+e"
new_tab = "alt+n"
close_tab = "alt+q"
previous_tab = "alt+9"
next_tab = "alt+0"

# Workspace and client session
new_workspace = "alt+shift+n"
