# Reload config: tmux source-file ~/.config/tmux/tmux.conf


# COMMON

set -g default-terminal             "tmux-256color"             # Enable 256 color support
set -ga terminal-overrides          ",*:RGB"
set -g terminal-features            "xterm*:RGB,tmux*:RGB"

set -g history-limit                1000                        # History size
set -g mouse                        on                          # Enable mouse support
set -g set-clipboard                on                          # Enable clipboard

set  -s escape-time                 0                           # Disable delay before escape

set -g base-index                   1                           # Window index starts with 1
setw -g pane-base-index             1                           # Pane index starts with 1


# STYLE

# Pane devider line style
set -g pane-border-lines            single
set -g pane-border-style            "fg=colour240"
set -g pane-active-border-style     "fg=colour68"


# STATUS BAR

set -g status-bg                    colour235
set -g status-fg                    colour250
set -g status-left                  "#[fg=colour68,bold]#S#[fg=colour240] <> "
set -g status-right                 "#(whoami)@#h #[fg=colour240] #[fg=colour68]%H:%M #[fg=colour240]"

setw -g window-status-current-style "fg=colour68,bg=colour235"
setw -g window-status-separator     "  "


# PANE

# Basic controls
bind -n M-w                         kill-pane                   # Close pane

# Select
bind -n M-h                         select-pane -L              # Go to left pane
bind -n M-l                         select-pane -R              # Go to right pane
bind -n M-k                         select-pane -U              # Go to top pane
bind -n M-j                         select-pane -D              # Go to bottom pane

# Split
bind -n M-h                         split-window -v             # Split vertically
bind -n M-v                        split-window -h             # Split horizontally

# WINDOW

# Basic controls
bind -n M-e                         choose-tree -w              # Show windows and sessions

bind -n M-n                         new-window                  # Create new window
bind -n M-q                         kill-window                 # Kill current window

# Switch
bind -n M-9                         previous-window             # Go to previous window
bind -n M-0                         next-window                 # Go to next window

bind -n M-1                         select-window -t 1
bind -n M-2                         select-window -t 2
bind -n M-3                         select-window -t 3
bind -n M-4                         select-window -t 4
bind -n M-5                         select-window -t 5

# SESSION

# Basic controls
bind -n M-N                         new-session

bind -n M-d                         detach
bind -n M-Q                         confirm-before -p "Quit session? (y/n)" kill-session

# Auto-kill numbered sessions on terminal close, keep named ones (e.g. main)
set-hook -g client-detached 'if-shell -F "#{m:#{session_name},^[0-9]+$}" "kill-session"'
