# COMMON

# Enable 256 color support
set -g default-terminal         "tmux-256color"
set -ga terminal-overrides      ",*:RGB"

# History size
set -g history-limit            1000

# Enable mouse support
set -g mouse                    on

# Enable clipboard
set -g set-clipboard            on

# Disable delay before escape
set  -s escape-time             0

# Pane devider line style
set -g pane-border-lines        double

# Pane and window index starts with 1
set -g base-index               1
setw -g pane-base-index         1


# PANE

# Basic controls
bind -n M-C-w                     kill-pane

# Select
bind -n M-C-h                     select-pane -L
bind -n M-C-l                     select-pane -R
bind -n M-C-k                     select-pane -U
bind -n M-C-j                     select-pane -D


# WINDOW

# Basic controls
bind -n M-C-W                     choose-tree -w

bind -n M-C-n                     new-window          
bind -n M-C-q                     kill-window

# Switch
bind -n M-C-]                     next-window         \; display-message "Window: #{window_index}"
bind -n M-C-[                     previous-window     \; display-message "Window: #{window_index}"

bind -n M-C-1                     select-window -t 1  \; display-message "Window: #{window_index}"
bind -n M-C-2                     select-window -t 2  \; display-message "Window: #{window_index}"
bind -n M-C-3                     select-window -t 3  \; display-message "Window: #{window_index}"
bind -n M-C-4                     select-window -t 4  \; display-message "Window: #{window_index}"
bind -n M-C-5                     select-window -t 5  \; display-message "Window: #{window_index}"
bind -n M-C-6                     select-window -t 6  \; display-message "Window: #{window_index}"
bind -n M-C-7                     select-window -t 7  \; display-message "Window: #{window_index}"
bind -n M-C-8                     select-window -t 8  \; display-message "Window: #{window_index}"
bind -n M-C-9                     select-window -t 9  \; display-message "Window: #{window_index}"

# Split
bind -n M-C--                     split-window -v
bind -n M-C-\\                    split-window -h


# SESSION

# Basic controls
bind -n M-C-N                     new-session
bind -n M-C-d                     detach
bind -n M-C-Q                     confirm-before -p "Quit session? (y/n)" kill-session
