---
brew_packages:
  bootstrap:
    - stow
    - git-lfs
  extensions:
    - starship
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - tmux
    - pfetch-rs
    - zoxide
    - fzf
    - eza
  cli_tools:
    - yazi
    - neovim
    - btop
    - nvtop
    - opencode
    - lazygit
    - fastfetch
    - zip
  optional:
    - taproom
    - superfile
    - tio
    - go
    - nvm
    - rustup
    - uv
    - sdkman-cli
    - yt-dlp
    - ffmpeg-full
    - imagemagick-full
    - mailsy
  taps:
    - sdkman/tap
  fonts:
    - font-jetbrains-mono-nerd-font
    - font-hack-nerd-font

linux_nerd_fonts:
  - name: JetBrainsMono
    archive: JetBrainsMono.tar.xz
  - name: Hack
    archive: Hack.tar.xz
