---
brew_packages:
  extensions:
    - starship
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - tmux
    - pfetch-rs
    - zoxide
    - eza
  cli_tools:
    - yazi
    - neovim
    - btop
    - nvtop
    - opencode
    - lazygit
    - fastfetch
  optional:
    - taproom
    - superfile
    - go
    - nvm
    - rustup
    - uv
    - yt-dlp
    - ffmpeg-full
    - imagemagick-full
    - mailsy
  taps:
    - gromgit/brewtils
  fonts:
    - font-jetbrains-mono-nerd-font
    - font-hack-nerd-font
