---
common_packages:
  arch:
    - sudo
    - git
    - git-lfs
    - curl
    - openssh
    - zsh
    - nano
    - stow
    - file
    - wl-clipboard
    - fontconfig
    - xz
  debian:
    - sudo
    - git
    - git-lfs
    - curl
    - ssh
    - zsh
    - nala
    - nano
    - stow
    - file
    - wl-clipboard
    - build-essential
    - fontconfig
    - xz-utils
  fedora:
    - sudo
    - git
    - git-lfs
    - curl
    - openssh-clients
    - zsh
    - nano
    - stow
    - file
    - wl-clipboard
    - gcc # sdkman
    - fontconfig
    - xz
