---
- name: Homebrew. Define brew path
  set_fact:
    brew_bin: /home/linuxbrew/.linuxbrew/bin/brew
  tags: [brew]

- name: Homebrew. Check existing installation
  stat:
    path: "{{ brew_bin }}"
  register: brew_bin_stat
  tags: [brew]

- name: Homebrew. Configure /home/linuxbrew directory
  file:
    path: "/home/linuxbrew"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: "0755"
  become: true
  when: not brew_bin_stat.stat.exists
  tags: [brew]

- name: Homebrew. Run installation script
  shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    HOMEBREW_NO_ANALYTICS: 1
    HOMEBREW_NO_AUTO_UPDATE: 1
  when: not brew_bin_stat.stat.exists
  tags: [brew]

- name: Homebrew. Show version
  command: "{{ brew_bin }} --version"
  register: brew_version_check
  changed_when: false
  tags: [brew]

- name: Homebrew. Version info
  debug:
    msg: "Linuxbrew version: {{ brew_version_check.stdout }}"
  tags: [brew]

- name: Homebrew. Load packages list
  include_vars: pkgs/brew_packages.yml
  tags: [brew]

- name: Homebrew. Install shell prompt extensions
  community.general.homebrew:
    name: "{{ brew_packages.extensions }}"
    state: present
  when: brew_bin_stat.stat.exists
  tags: [brew]

- name: Homebrew. Install CLI tools
  community.general.homebrew:
    name: "{{ brew_packages.cli_tools }}"
    state: present
  when: brew_bin_stat.stat.exists
  tags: [brew]

- name: Homebrew. Install fonts
  community.general.homebrew:
    name: "{{ brew_packages.fonts }}"
    state: present
  when: brew_bin_stat.stat.exists
  tags: [brew]

- name: Homebrew. Tap additional repositories
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_packages.taps }}"
  when:
    - brew_bin_stat.stat.exists
    - extended | bool
  tags: [brew]

- name: Homebrew. Trust taps
  shell: "{{ brew_bin }} trust {{ item }}"
  loop: "{{ brew_packages.taps }}"
  when:
    - brew_bin_stat.stat.exists
    - extended | bool
  tags: [brew]

- name: Homebrew. Install optional packages
  community.general.homebrew:
    name: "{{ brew_packages.optional }}"
    state: present
  when:
    - brew_bin_stat.stat.exists
    - extended | bool
  tags: [brew]
