---
- name: Common. Load packages
  include_vars: pkgs/common_packages.yml

- name: Common. Install packages (Arch Linux)
  become: true
  when: ansible_facts["os_family"] == "Archlinux"
  pacman:
    name: "{{ common_packages.arch }}"
    state: present

- name: Common. Install packages (Debian/Ubuntu)
  become: true
  when: ansible_facts["os_family"] == "Debian"
  apt:
    name: "{{ common_packages.debian }}"
    state: present
