---
- name: Load common packages
  include_vars: pkgs/common_packages.yml

- name: Install common packages (Arch Linux)
  become: true
  when: ansible_facts["os_family"] == "Archlinux"
  pacman:
      name: "{{ common_packages.arch }}"
      state: present

- name: Install common packages (Debian/Ubuntu)
  become: true
  when: ansible_facts["os_family"] == "Debian"
  apt:
      name: "{{ common_packages.debian }}"
      state: present
