"$schema" = 'https://starship.rs/config-schema.json'

right_format = """
$git_branch
$git_commit
$git_state
$git_status
$os
"""

[os]
# disabled = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"


[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"


[directory]
read_only = " 󰌾"

[hostname]
ssh_symbol = " "

[git_branch]
symbol = " "

[nix_shell]
symbol = " "

[docker_context]
symbol = " "

[container]
symbol = " "

[kubernetes]
symbol = "󱃾 "

[conda]
symbol = " "


[bun]
symbol = " "
format = "via [$symbol]($style)"

[c]
symbol = " "
format = "via [$symbol($name)]($style)"

[cpp]
symbol = " "
format = "via [$symbol($name)]($style)"

[cmake]
symbol = " "
format = "via [$symbol]($style)"

[crystal]
symbol = " "
format = "via [$symbol]($style)"

[dart]
symbol = " "
format = "via [$symbol]($style)"

[deno]
symbol = " "
format = "via [$symbol]($style)"

[dotnet]
symbol = " "
format = "[$symbol(🎯 $tfm )]($style)"

[golang]
symbol = "󰟓 "
format = "via [$symbol]($style)"

[gradle]
symbol = " "
format = "via [$symbol]($style)"

[haskell]
symbol = " "
format = "via [$symbol]($style)"

[haxe]
symbol = " "
format = "via [$symbol]($style)"

[java]
symbol = " "
format = "via [$symbol]($style)"

[julia]
symbol = " "
format = "via [$symbol]($style)"

[kotlin]
symbol = " "
format = "via [$symbol]($style)"

[lua]
symbol = " "
format = "via [$symbol]($style)"

[maven]
symbol = " "
format = "via [$symbol]($style)"

[meson]
symbol = "󰔷 "
format = "via [$symbol]($style)"

[nim]
symbol = " "
format = "via [$symbol]($style)"

[nodejs]
symbol = "󰎙 "
format = "via [$symbol]($style)"

[perl]
symbol = " "
format = "via [$symbol]($style)"

[php]
symbol = " "
format = "via [$symbol]($style)"

[python]
symbol = " "
format = "via [$symbol]($style)"

[ruby]
symbol = " "
format = "via [$symbol]($style)"

[rust]
symbol = "󱘗 "
format = "via [$symbol]($style)"

[scala]
symbol = " "
format = "via [$symbol]($style)"

[swift]
symbol = " "
format = "via [$symbol]($style)"

[zig]
symbol = " "
format = "via [$symbol]($style)"

[os.symbols]
Alpine = " "
ALTLinux = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
Elementary = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
Kali = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = "󰺡 "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "